export const productsData = [
  {
    id: 1,
    name: "Sleek Edge Golden Band Ring",
    price: 1539.3,
    rating: 5,
    reviews: 3,
    desc: "",
    catogery: "New Areivals",
    img: "https://palmonas.com/cdn/shop/files/RG0065-6.jpg?v=1762003558",
    img2: "https://palmonas.com/cdn/shop/files/DSC00498.webp?v=1762003558"
  },
  {
    id: 2,
    name: "Aurelia Angel Wing Ring",
    price: 1539.3,
    rating: 5,
    reviews: 1,
    desc: "",
    catogery: "New Arrivals",
    img: "https://palmonas.com/cdn/shop/files/RG0077.webp?v=1761139258&width=900",
  },
  {
    id: 3,
    name: "Bolt Signature Silver Cuban Chain",
    price: 1749.0,
    rating: 4,
    reviews: 2,
    desc: "",
    img: "https://palmonas.com/cdn/shop/files/DSC00564_7be16611-c2bb-405a-a9d8-082d6dceb841.jpg?v=1761150835&width=900",
  },
  {
    id: 4,
    name: "Celestia Sparkle Glow Ring",
    price: 2379.30,
    rating: 5,
    reviews: 1,
    desc: "",
    img: "https://palmonas.com/cdn/shop/files/RG0075.webp?v=1761139969&width=900",
  },
  {
    id: 5,
    name: "Celestia Sparkle Glow Ring",
    price: 2589.30,
    rating: 5,
    reviews: 1,
    desc: "",
    img: "https://palmonas.com/cdn/shop/files/NK0215.webp?v=1761139192&width=900",
  },
  {
    id: 6,
    name: "Dual Tone Auric Infinity Ring",
    price: 2379.00,
    rating: 5,
    reviews: 1,
    desc: "",
    img: "https://palmonas.com/cdn/shop/files/RG0062-7.webp?v=1760697064&width=900",
  },
  {
    id: 7,
    name: "Diamond Affair Bracelet",
    price: 2553.00,
    rating: 5,
    reviews: 367,
    desc: "",
    img: "https://palmonas.com/cdn/shop/files/DIAMONDAFAIR_e5bce936-e512-4d65-8312-c3605398cc2e.jpg?v=1744527093",
    img2: "https://palmonas.com/cdn/shop/files/BR064-G_208378bf-3256-4c89-ad69-b75e4aaccc35.jpg?v=1744527093",
  },
  {
    id: 8,
    name: "Hearts All Over Bracelet",
    price: 2229.00,
    rating: 5,
    reviews: 1587,
    desc: "",
    img: "https://palmonas.com/cdn/shop/files/01_e869a853-ae2b-4543-8f22-61455b80f6a6.webp?v=1744528231",
    img2: "https://palmonas.com/cdn/shop/files/product_1_4ece22f3-45f4-4c3c-b306-d91f8c41fe28.jpg?v=1754386754",
  },
  {
    id: 9,
    name: "Athena Solitaire Hoop Earrings",
    price: 2258.00,
    rating: 5,
    reviews: 658,
    desc: "Sleek and elegant, these 18k gold plated Athena solitaire hoop earrings feature sparkling white cubic zirconia stones for a refined, minimalist look. Their versatile hoop design adds subtle sophistication to any outfit, while the waterproof and anti-tarnish finish ensures lasting shine. Perfect for everyday wear, office styling, or evening occasions, these earrings are a timeless addition to your jewellery collection. STYLING TIP: Pair with casual tops, button-down shirts, or simple dresses for subtle sparkle.",
    img: "https://palmonas.com/cdn/shop/files/PM-EARRINGS-032_3_0040.jpg?v=1744528692",
    img2: "https://palmonas.com/cdn/shop/files/PM-EARRINGS-032_1_ca866188-eb2f-491f-ae6d-e42e9501725b.jpg?v=1744528692",
  },
  {
    id: 10,
    name: "Classic Emerald Necklace",
    price: 2129.00,
    rating: 5,
    reviews: 502,
    catogery: "Shraddha's Favourite",
    desc: "The Classic Emerald Necklace features a vibrant green emerald pendant set on a sleek 18k gold-tone chain, exuding elegance and sophistication. Crafted in stainless steel with a durable gold finish, this waterproof and anti-tarnish necklace enhances casual, office, or evening outfits, making it a versatile accessory for everyday wear or special occasions. STYLING TIP: Wear with soft dresses or casual blouses for effortless everyday charm.",
    img: "https://palmonas.com/cdn/shop/files/NK-40_1_0040.jpg?v=1744524127",
    img2: "https://palmonas.com/cdn/shop/files/product_images_f349bdcc-e064-4744-9be2-2e09dcdd28c5.jpg?v=1744524127&width=900",
  },
  {
    id: 11,
    name: "Round Solitaire Necklace",
    price: 2644.00,
    rating: 5,
    reviews: 429,
    desc: "",
    img: "https://palmonas.com/cdn/shop/files/NK390-1.jpg?v=1744526106",
    img2: "https://palmonas.com/cdn/shop/files/NK390_1_c7692c2e-31cc-4df0-8295-fb49ba317f9b.jpg?v=1744526106",
  },
  {
    id: 12,
    name: "Gilded Rings Layered Necklace",
    price: 1899.00,
    rating: 5,
    reviews: 280,
    desc: "",
    catogery: "Best Seller",
    img: "https://palmonas.com/cdn/shop/files/PMW01NC023_1.jpg?v=1744523751&width=900",
    img2: "https://palmonas.com/cdn/shop/files/PMW01NC023_4_c503499e-0334-4432-be9f-a0f752ff7bf2.jpg?v=1744523751&width=900",
  },
  {
    id: 13,
    name: "Forever Yours 925 Silver Ring",
    price: 2120.00,
    rating: 5,
    reviews: 14,
    catogery: 'Fine Silver',
    desc: "The Forever Yours Ring is a timeless and elegant addition to any jewellery collection. Crafted from 925 sterling silver with rhodium plating, it features a classic solitaire design that exudes sophistication and romance. Durable and versatile, this ring adds subtle sparkle and elegance, making it perfect for everyday wear or special occasions, enhancing any outfit with refined charm. STYLING TIP: Combine with delicate bracelets and a tailored blazer for a polished, professional style.",
    img: "https://palmonas.com/cdn/shop/files/LR023_3_0040.jpg?v=1744517804",
    img2: "https://palmonas.com/cdn/shop/files/Capture_One_Catalog0555_1.jpg?v=1744517805",
    vid1: "https://palmonas.com/cdn/shop/videos/c/vp/bba5c3142bce43a89a1fcffc3a6791a0/bba5c3142bce43a89a1fcffc3a6791a0.HD-1080p-7.2Mbps-40342913.mp4?v=0"
  },
  {
    id: 14,
    name: "925 Silver Blush Halo Ring",
    price: 3883.00,
    rating: 5,
    reviews: 4,
    catogery: 'Fine Silver',
    desc: "The Blush Halo Ring is a dazzling addition to any jewellery collection. Crafted from 925 sterling silver with rhodium plating, it features a cluster of white cubic zirconia stones in a halo design, creating a sparkling, eye-catching effect. Durable and versatile, this ring offers timeless elegance and sophistication, making it perfect for everyday wear or special occasions while complementing any outfit. STYLING TIP: Pair with a black dress and delicate silver bracelets for elegant evening wear.",
    img: "https://palmonas.com/cdn/shop/files/LR031_3_0040.jpg?v=1744517922&width=900",
  },
  {
    id: 15,
    name: "Wavy Chevron 9KT Gold Lab Grown Diamond Earrings",
    price: 39786.17,
    rating: 5,
    reviews: 1,
    desc: "These earrings showcase a captivating wavy chevron pattern, embellished with radiant lab-grown diamonds for an effortlessly chic look. Ideal for those who adore geometric artistry with a modern twist, they bring balance and sophistication to any style. Perfect for adding contemporary flair to your jewelry collection. Make it truly yours with Palmonas! Personalize this elegant design in 9KT, available in White, Yellow, or Rosegold tone. Expertly crafted to perfection, this timeless piece reflects your style. Slight weight variations may occur as each piece is handcrafted.",
    catogery: "9KT Finer Gold",
    img: "https://palmonas.com/cdn/shop/files/RG0062-7.webp?v=1760697064&width=900",
    img2: "https://palmonas.com/cdn/shop/files/SRWER31_R0000.jpg?v=1760161824&width=900",
    img3: "https://palmonas.com/cdn/shop/files/SRWER31_S_1_0000.jpg?v=1760161824&width=900",
  },
  {
    id: 16,
    name: "Golden Heart Charm Chain Necklace",
    price: 2475.00,
    rating: 5,
    reviews: 113,
    catogery: "Emily In Paris",
    desc: "Wear your heart in gold. Crafted from durable stainless steel and plated in luminous 18K gold, our Golden Heart Charm Chain Necklace embodies elegance with a touch of sentiment. Thoughtfully designed just for you, it’s the perfect balance of charm and sophistication. STYLING TIP: Pair it with dainty gold hoops and a white satin blouse for a soft, romantic look.",
    img: "https://palmonas.com/cdn/shop/files/PMW01NC079-1_e964fd09-1bdf-4fd9-b190-6eb08d2dc153.jpg?v=1744521539",
    img2: "https://palmonas.com/cdn/shop/files/DSC00336_673e33c8-75ae-411f-9de1-0eb9547c7131.jpg?v=1744521539",
  },
  {
    id: 17,
    name: "Gold Bow and Tassel Drop Earrings",
    price: 2475.00,
    rating: 5,
    reviews: 46,
    catogery: "Emily In Paris",
    desc: "Playful yet elegant, these 18k gold plated Gold Bow and Tassel drop earrings feature a chic bow design paired with delicate tassels, creating movement and charm with every turn. The polished gold finish ensures lasting shine, while the waterproof and anti-tarnish properties keep them flawless. Perfect for both casual and festive occasions, these earrings make a statement while maintaining sophistication. STYLING TIP: Style with satin dresses, slip gowns, or cocktail outfits to let the gold shine and add movement to your look.",
    img: "https://palmonas.com/cdn/shop/files/PMW01ER157.jpg?v=1744522091",
    img2: "https://palmonas.com/cdn/shop/files/PMW01ER157_2_36803141-2426-422f-90a7-c16fe602f105.jpg?v=1744522091",
  },
  {
    id: 18,
    name: "Rainbow of Gems Layered Necklace",
    price: 3675.00,
    rating: 5,
    reviews: 23,
    catogery: "Emily In Paris",
    desc: "Bright, playful, and fashion-forward, the Rainbow of Gems Layered Necklace brings a cascade of multicolour pearls and synthetic stones to your jewellery collection. Crafted in stainless steel with an 18k gold tone finish, its layered design creates depth and movement, making it a standout statement piece. Perfect for adding a pop of colour and sparkle to both casual and dressy looks. STYLING TIP: Style over a flowy maxi dress with earthy tones for a festival-inspired look.",
    img: "https://palmonas.com/cdn/shop/files/PMW01NC068-2_d6ab54cf-5218-411d-a0a4-e679d82991ac.jpg?v=1744521979&width=900",
    img2: "https://palmonas.com/cdn/shop/files/DSC00509_6bac0c31-d507-461b-a625-127db3a5bb75.jpg?v=1744521979&width=900",
  },
  {
    id: 19,
    name: "Multi-Stand Gold Necklace",
    price: 2875.00,
    rating: 5,
    reviews: 17,
    catogery: "Emily In Paris",
    desc: "Bold, contemporary, and versatile, the Multi-Stand Gold Necklace is crafted in stainless steel, featuring a layered lariat design that adds dimension and elegance to any outfit. Perfect for making a statement, this necklace elevates both casual ensembles and evening looks with its chic, modern appeal. STYLING TIP: Pair with a simple tee and jeans to let the layered design stand out.",
    img: "https://palmonas.com/cdn/shop/files/PMW01NC072-1_77b97a9d-265d-4441-89e6-ab48c3a9d696.jpg?v=1744521942&width=900",
    img2: "https://palmonas.com/cdn/shop/files/DSC00703_70ddce09-236f-4275-98c3-20afdd57b803.jpg?v=1744521942&width=900",
  },
  {
    id: 20,
    name: "Golden Spill Necklace",
    price: 1899.00,
    rating: 5,
    reviews: 26,
    catogery: "Shraddha's Favourite",
    desc: "Elegant and contemporary, the Golden Spill Necklace is crafted in stainless steel, featuring a sleek, flowing design that adds subtle sophistication to any outfit. Its short necklace style makes it perfect for layering or wearing solo, bringing a modern, polished touch to both casual and evening ensembles. STYLING TIP: Complement a strapless or off-shoulder dress to let the necklace catch the light.",
    img: "https://palmonas.com/cdn/shop/files/NK477.webp?v=1761797725&width=900",
    img2: "https://palmonas.com/cdn/shop/files/Artboard_2.jpg?v=1761797725&width=900",
  },
  {
    id: 21,
    name: "Glossy Enamel Ring",
    price: 1899.00,
    rating: 5,
    reviews: 11,
    catogery: "Shraddha's Favourite",
    desc: "The Glossy Enamel Ring is a vibrant statement piece crafted from stainless steel and coated in lustrous 18k gold tone. Its smooth enamel finish delivers a modern, playful touch while maintaining a polished and elegant appeal. Ideal for adding a pop of color and texture, this ring works for both casual and semi-formal occasions, letting your fingers stand out effortlessly. STYLING TIP: Combine with a tailored blazer and neutral blouse for subtle elegance with a twist.",
    img: "https://palmonas.com/cdn/shop/files/RG104-B-6_60057bbd-fd66-4dbe-9122-791a001c915e.jpg?v=1744527645&width=900",
    img2: "https://palmonas.com/cdn/shop/files/RG104-B.jpg?v=1744527645&width=900",
  },
  {
    id: 22,
    name: "Plain Chain Two Layer Necklace",
    price: 2258.00,
    rating: 5,
    reviews: 304,
    catogery: "Shraddha's Favourite",
    desc: "The Plain Chain Two Layer Necklace brings versatile elegance with its minimalist layered design. Crafted in stainless steel with a radiant 18k gold tone, this waterproof and anti-tarnish necklace adds a chic, modern accent to any outfit. Perfect for casual, office, or evening wear, it enhances both everyday and festive ensembles with subtle sophistication. STYLING TIP: Style with soft tops or dresses for a refined everyday accent.",
    img: "https://palmonas.com/cdn/shop/files/PM-NECKLACE-170_1.jpg?v=1744528483&width=900",
    img2: "https://palmonas.com/cdn/shop/files/PM-NECKLACE-170-ML3.jpg?v=1745910304&width=900",
  },
  {
    id: 23,
    name: "Square Mirage Earrings",
    price: 1889.00,
    rating: 5,
    reviews: 10,
    catogery: "Shraddha's Favourite",
    desc: "Elevate your style with these 18k gold plated Square Mirage earrings, featuring a sleek geometric design that exudes modern elegance. Perfect for both casual and formal occasions, their bold yet minimalist look adds a sophisticated edge to any outfit. Waterproof and anti-tarnish, they maintain their shine and style wherever you go. STYLING TIP: Pair with structured blazers, tailored trousers, or a sheath dress for a professional, fashion-forward appearance.",
    img: "https://palmonas.com/cdn/shop/files/ER235_b4cd2cdc-0fd3-41d4-b408-d97002fc4e63.jpg?v=1750244184&width=900",
    img2: "https://palmonas.com/cdn/shop/files/ER235_0040.jpg?v=1750244184&width=900",
  },
  {
    id: 24,
    name: "Rope Chain | 6 MM",
    price: 2633.00,
    rating: 5,
    reviews: 202,
    catogery: "Demi-fine Jewellery",
    desc: "Bold, masculine, and timeless, this Rope Chain is crafted in stainless steel with a radiant 18k gold tone finish. Its twisted rope design exudes strength and sophistication, making it a versatile statement piece for men who appreciate classic, high-impact jewellery. Perfect for layering or wearing solo, this chain elevates both casual and formal looks with effortless style. STYLING TIP: Style over a crisp shirt or under a blazer for a subtle yet striking accent.",
    img: "https://palmonas.com/cdn/shop/products/1_182adae1-9887-4e14-9203-abf43125dfd4.jpg?v=1744527319&width=900",
    img2: "https://palmonas.com/cdn/shop/files/CHAIN-009-M_2.jpg?v=1751865579&width=900",
  },
  {
    id: 25,
    name: "Multi Stone Q Clasp Bracelet",
    price: 2258.00,
    rating: 5,
    reviews: 263,
    catogery: "Demi-fine Jewellery",
    desc: "The Palmonas Multi Q Clasp Bracelet brings everyday elegance with a hint of edge. Crafted in stainless steel, this piece blends boldness and beauty with its unique clasp design and subtle stone accents. A modern classic, it redefines what a stone bracelet can be. Part of our demi-fine jewellery line, it’s made for those who love their accessories to be a little different, a little daring, and highly versatile. Whether you stack it or style it solo, this gold bracelet for women adds a gleam of quiet confidence to your look. STYLING TIP: Pair it with your favourite watch or layer it with thin chains and cuffs. It's the piece that pulls your whole arm party together. From client meetings to coffee dates, this gold-plated jewellery essential is your 9 to 9 companion, polished, practical, and",
    img: "https://palmonas.com/cdn/shop/files/BR082-G.jpg?v=1744526804&width=900",
    img2: "https://palmonas.com/cdn/shop/files/BR082G.jpg?v=1744526804&width=900",
  },
];
